[module]
  [[module.imports]]
    # upgrade with:
    # hugo mod get github.com/hugomods/icons
    path = 'github.com/hugomods/icons'
    disable = false
  [[module.imports]]
    # upgrade with:
    # hugo mod get github.com/hugomods/icons/vendors/font-awesome
    path = 'github.com/hugomods/icons/vendors/font-awesome'
    disable = false
