
title = "I'm Jane Doe"
author = "Jane Doe"
#copyright = "2020-2021"
description = "Call me Jane"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = []
mainSections = ["post", "blog"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
postSectionName = "blog"  # Deprecated: use postSections instead
postSections = ["post", "blog"]  # List of post sections that support comments and post features
# relatedPosts = true
# numberOfRelatedPosts = 3
# useSimplePostLists = false
# excludeMultipleSeriesFromRelated = true

# Full link to license
#license = "https://creativecommons.org/licenses/by/4.0/"

# disableTitleCapitalization = true
# defaultMobileNavPosition = "bottom"
# disableNavPosSwitcher = false
# disableArchiveTitleStyling = true
# disableTitleCapitalization = true
# showMetaInThumbnailOverlay = true
# disableHeaderAnimation = true
# disableSidebarAnimation = false
# disableDesktopSidebarAnimation = true

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

# Sidebar/Content Ratio
# contentratio = 0.6

# centerTocInSidebar = false
# showPostSectionsInSidebar = true
# highlightCurrentSection = true
# showCurrentTaxonomyInSidebar = true
# highlightCurrentTaxonomy = true
# listTaxonomyByCount = true

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"
# trackerScriptName = "mycustomscriptname.js"

[imageResize]
# min = 300
# max = 900
# increment = 200

[flexSearch]
# maxResultsCount = 5
# disableNavbarExpansion = false
# disableSidebarExpansion = false
# suggestRecentPostsWhenNoResults = true
# suggestRelatedPostsWhenNoResults = true
# noResultsSuggestionCount = 3
# optimizeContent = true   # set to false to index full post content (data-intensive)

## these are only used if optimizeContent = true (disable any by setting to -1)
# indexHeadings = true     # index all the headings of the post
# minWordLength = 3        # words under this length won't be indexed
# topWordsCount = 50       # index the top N words from the post
# keySentencesCount = 2    # index first and last N sentences of the post
# paragraphWordsCount = 3  # index first and last N words of each paragraph
# paragraphWordsLimit = -1 # disable paragraph word indexing when -1
# commonWords = []         # add words to exclude them from indexing

# progressive web app (PWA) settings
[pwa]
  enable = true
  # manifest_file = "site.webmanifest"
  offline_image = 'https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExaTN3MDE3YXZseXNxYnYwejl0cHdjMTBqa2lwaDRpbXl0b2ZncjhndSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/XIjw2n4kUXxuqDn7dN/giphy.gif'
  offline_image_marquee = true
  [[pwa.precaches]]
    url = '/'
  [[pwa.precaches]]
    url = 'https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExaTN3MDE3YXZseXNxYnYwejl0cHdjMTBqa2lwaDRpbXl0b2ZncjhndSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9cw/XIjw2n4kUXxuqDn7dN/giphy.gif'
  [pwa.caches]
    [pwa.caches.font]
      strategy = "cache-first"
      origins = []
      max_age = 2592000 # 30d
    [pwa.caches.image]
      strategy = "cache-first"
      origins = []
      max_age = 2592000 # 30d
    [pwa.caches.script]
      strategy = "cache-first"
      origins = []
      max_age = 2592000 # 30d
    [pwa.caches.style]
      strategy = "cache-first"
      origins = []
      max_age = 2592000 # 30d

## Social links
# use 'fa-brands' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
vendor = "fab"
icon = "linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[socialIcons]]
vendor = "fab"
icon = "github"
title = "GitHub"
url = "https://github.com/lxndrblz/anatole/"

[[socialIcons]]
vendor = "fab"
icon = "instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[socialIcons]]
vendor = "fas"
icon = "envelope"
title = "e-mail"
url = "mailto:mail@example.com"

[mermaid]
# enable = true

[[shareIcons]]
name = "share"
vendor = "fas"
icon = "share-nodes"
title = "Copy Link"
colorIndex = 4

[[shareIcons]]
name = "facebook"
vendor = "fab"
icon = "facebook"
url = "https://www.facebook.com/sharer/sharer.php?u=:url"
title = "Share on Facebook"
colorIndex = 1

[[shareIcons]]
name = "twitter"
vendor = "fab"
icon = "twitter"
url = "https://x.com/intent/post/?url=:url&text=:title"
title = "Share on X"
colorIndex = 2

[[shareIcons]]
name = "linkedin"
vendor = "fab"
icon = "linkedin"
url = "https://www.linkedin.com/shareArticle?mini=true&url=:url&title=:title&source=:source"
title = "Share on LinkedIn"
colorIndex = 5

[[shareIcons]]
name = "email"
vendor = "fas"
icon = "envelope"
url = "mailto:?subject=:title&body=:url"
title = "Share via Email"
colorIndex = 3
